version: 2.1
orbs:
  terraform: sous-chefs/terraform@dev:latest

jobs:
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - terraform/lint_terraform
      - run:
          name: Terraform Plan
          command: |
            terraform init
            terraform plan
  apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            terraform init
            terraform apply --auto-approve

workflows:
  version: 2
  build:
    jobs:
      - plan:
          context: Terraform
          filters:
            branches:
                ignore:
                  - master
      - apply:
          context: Terraform
          filters:
            branches:
                only:
                  - master
