---
version: 2.1
orbs:
  sous-chefs: sous-chefs/kitchen@2

workflows:
  lint:
    jobs:
      - sous-chefs/validate_terraform:
          name: validate terraform
          context: Terraform
      - sous-chefs/lint_terraform:
          name: lint terraform
