---
version: 2.1
orbs:
  sous-chefs: sous-chefs/kitchen@2

workflows:
  lint:
    jobs:
      - sous-chefs/validate_terraform:
          name: validate terraform
          context: Terraform
      - sous-chefs/lint_terraform:
          name: lint terraform
  test:
    jobs:
    - plan:
        context: Terraform
        filters:
          branches:
            ignore: [master]
    - apply:
        context: Terraform
        filters:
          branches:
            only: [master]
jobs:
  plan:
    executor: terraform
    steps:
      - checkout
      - init
      - plan

  apply:
    executor: terraform
    steps:
      - checkout
      - init
      - apply_auto_approve

commands:
  init:
    description: Initialise Terraform
    steps:
      - run:
          command: terraform init -lock=false -upgrade -input=false
  plan:
    description: Plan Terraform
    steps:
      - run:
          command: terraform plan -input=true -parallelism=50
  apply_auto_approve:
    description: Apply Terraform
    steps:
      - run:
          command: terraform apply --auto-approve

executors:
  terraform:
    docker:
      - image: hashicorp/terraform
