---
version: 2.1

jobs:
  test:
    executor: terraform/terraform
    steps:
      - checkout
      - terraform/terraform_fmt
      - terraform/terraform_validate
      - init
      - plan

  apply:
    executor: terraform/terraform
    steps:
      - checkout
      - apply_auto_approve

workflows:
  test:
    jobs: [test]
    filters:
        branches: [ignore: master]

orbs:
  terraform: devops-workflow/terraform@0.0.1

commands:
  init:
    description: Initialise Terraform
    steps:
      - run:
          command: terraform init -lock=false -upgrade -input=false
  plan:
    description: Plan Terraform
        steps:
          - run:
              command: terraform init -lock=false -upgrade -input=false
