version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: |
          terraform init
          terraform plan -out sous.plan
      - persist_to_workspace:
        root: .
        paths: .
  apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          terraform init
          terraform apply sous.plan --auto-approve
      - attach_workspace:
          at: .

workflows:
  version: 2
  build_and_test:
    jobs:
      - plan:
          context: Terraform
      - hold:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold
          context: Terraform
