version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: |
          terraform init
          terraform plan -out sous.plan
      - persist_to_workspace:
          root: .
          paths: .
  apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          terraform init
          terraform apply --auto-approve sous.plan

workflows:
  version: 2
  build_and_test:
    jobs:
      - plan:
          context: Terraform
      - hold:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold
          context: Terraform
