version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: |
          terraform init
          terraform plan
  apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: |
          terraform init
          terraform apply --auto-approve

workflows:
  version: 2
  build:
    jobs:
      - plan:
          context: Terraform
          filters:
            branches:
                ignore:
                  - master
      - apply:
          context: Terraform
          filters:
            branches:
                only:
                  - master
