---
version: 2.1

workflows:
  test:
    jobs:
    - test:
        context: Terraform
        filters:
          branches:
            ignore: [master]
    - apply:
        context: Terraform
        filters:
          branches:
            only: [master]
jobs:
  test:
    executor: terraform
    steps:
    - checkout
    - terraform/terraform_fmt
    - terraform/terraform_validate
    - init
    - plan

  apply:
    executor: terraform
    steps:
      - checkout
      - init
      - apply_auto_approve

orbs:
  terraform: devops-workflow/terraform@0.0.1

commands:
  init:
    description: Initialise Terraform
    steps:
      - run:
          command: terraform init -lock=false -upgrade -input=false
  plan:
    description: Plan Terraform
    steps:
      - run:
          command: terraform plan -input=true -parallelism=50
  apply_auto_approve:
    description: Apply Terraform
    steps:
      - run:
          command: terraform apply --auto-approve

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:0.11.14
