---
version: 2.1

jobs:
  test:
    executor: terraform/terraform
    steps:
      - checkout
      - terraform/terraform_fmt
      - terraform/terraform_validate

  # build:
  #   jobs:
  #     - plan:
  #         context: Terraform
  #         filters:
  #           branches:
  #               ignore:
  #                 - master
  #     - apply:
  #         context: Terraform
  #         filters:
  #           branches:
  #               only:
  #                 - master


workflows:
  test:
    jobs: [test]
    # filters:
    #     branches: [ignore: master]

orbs:
  terraform: devops-workflow/terraform@0.0.1
